### ISSUE TITLE
ERROR in MOOD installation

### ISSUE THREAD

**Issue by rahul-1209** [valence-labs/mood-experiments#6]
Hi, During the process of MOOD software installation. 
I successfully managed to install MAMBA and able to run the initial process of  

```
mamba env create -n mood -f env.yml 
conda activate mood
```

I am using --> python version `3.10.13`, pip version `23.3.2`
But when it comes to running the `pip install -e .` part, I am facing the error of 
  
```
Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      Traceback (most recent call last):
        File "/home/uottawa.o.univ/rravicha/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/uottawa.o.univ/rravicha/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/uottawa.o.univ/rravicha/.local/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 132, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-e1mq0tzs/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 441, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-e1mq0tzs/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-e1mq0tzs/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-e1mq0tzs/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-env-e1mq0tzs/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-e1mq0tzs/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 147, in setup
          _setup_distribution = dist = klass(attrs)
        File "/tmp/pip-build-env-e1mq0tzs/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 314, in __init__
          self.metadata.version = self._normalize_version(self.metadata.version)
        File "/tmp/pip-build-env-e1mq0tzs/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 350, in _normalize_version
          normalized = str(Version(version))
        File "/tmp/pip-build-env-e1mq0tzs/overlay/lib/python3.10/site-packages/setuptools/_vendor/packaging/version.py", line 198, in __init__
          raise InvalidVersion(f"Invalid version: '{version}'")
      setuptools.extern.packaging.version.InvalidVersion: Invalid version: 'dev'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.
```

I am not sure about this error but it is preventing me from installing the MOOD software.

Thanks,
Rahul.

**Comment by cwognum** [comment]
Hi @rahul-1209, 

Thank you for taking the time to report this issue! From what Github tells me, this is your first issue ever. It's all the more appreciated! 🚀 

I couldn't reproduce the issue in a fresh install locally on my own computer. For future reference, this is the exact line of commands I used: 
```
git clone git@github.com:valence-labs/mood-experiments.git
cd mood-experiments
mamba env create -n mood -f env.yml
conda activate mood
pip install -e .
```

Could you provide me with the following additional information: 
- The operating system you are using (e.g. Windows, Mac, Linux)
- The version of mamba that you are using (you can use `mamba --version`)
- The exact commands you used to install MOOD.

**Comment by David-Araripe** [comment]
@rahul-1209 , as a suggestion, you could also try installing the package directly from Pip. This could work through:
`python -m pip install git+https://github.com/valence-labs/mood-experiments.git`

Or, if you need to have the package as an editable file so that you can make your modifications, you can run:
`python -m pip install -e git+https://github.com/valence-labs/mood-experiments.git#egg=mood-experiments`

**Comment by rahul-1209** [comment]
Hi @cwognum and @David-Araripe, Thanks alot for your suggestions. 
To answer @cwognum - I am using 
Ubuntu version - 20.04 
Mamba version - 1.5.5 
Setuptools version - 68.2.2

The exact commands are - Once I downloaded the Zip file of MOOD-experiments form the github page I extracted it and then 
cd mood-experiments-main/
mamba env create -n mood -f env.yml
conda activate mood -- till here everything looks fine. 
I was facing the above mentioned error only while running 
pip install -e .

Update: 
The 1st work around mentioned by @David-Araripe of using
python -m pip install git+https://github.com/valence-labs/mood-experiments.git --> it  works.
when I run - 
mood --help
got the output 

Usage: mood [OPTIONS] COMMAND [ARGS]...

Options:
  --help  Show this message and exit.

Commands:
  rct      Randomly sample a configuration for training
  scripts  CLI for the various stand-alone scripts of MOOD
  tune     Hyper-param search for a model with a specific configuration

However, the installation as an editable file 
python -m pip install -e git+https://github.com/valence-labs/mood-experiments.git#egg=mood-experiments 
failed  with an an error - 
WARNING: Generating metadata for package mood-experiments produced metadata for project name mood. Fix your #egg=mood-experiments fragments.
Discarding git+https://github.com/valence-labs/mood-experiments.git#egg=mood-experiments: Requested mood from git+https://github.com/valence-labs/mood-experiments.git#egg=mood-experiments has inconsistent name: expected 'mood-experiments', but metadata has 'mood'
ERROR: Could not find a version that satisfies the requirement mood-experiments (unavailable) (from versions: none)
ERROR: No matching distribution found for mood-experiments (unavailable)

I am also curious to know what would be the difference and advantage to use the editable version over the non-editable version in MOOD (or) can I carry on by using non-editable one?

Thanks much for your suggestions once again. 
Rahul.

**Comment by David-Araripe** [comment]
Hi @rahul-1209 , apologies for the confusion. The correct command to have it installed as an editable version would be `python -m pip install -e git+https://github.com/valence-labs/mood-experiments.git#egg=mood` 

If you'd like to know more, you can read what's the meaning of `pip install -e` by `pip install -h`. You will see that the -e is described as:

> Install a project in editable mode (i.e. setuptools "develop mode") from a local project path or a VCS url.

The advantage of installing it this way is that **if you're planning on making changes to the source code**, your changes will directly be applied to your installation copy. Whereas a regular install with `pip install` would require you to re-install the package so that your changes are applied to your installation copy.

I don't fully understand why installing it as an editable version requires you to have `#egg=mood`, but it needs to be the name of the Python project, which you can see here: https://github.com/valence-labs/mood-experiments/blob/main/pyproject.toml#L6.

**Comment by cwognum** [comment]
Thanks for providing me with further information, @rahul-1209! 

And I think @David-Araripe did a perfect job at answering some of your questions! Sorry for the confusion between package name and repository name. No real good reason for it...

Given that the install from Github directly seems to work, whereas the installation of the locally downloaded files does not, maybe something is wrong with the files you have locally. Two suggestions: 

- Try installing with `python -m pip install -e .`. It could be that due to having various python versions installed on your system, something goes wrong there. This should make sure the right `pip` executable is used. 
- Instead of downloading as ZIP, try downloading a fresh copy through [Git](https://git-scm.com/) directly, with `git clone https://github.com/valence-labs/mood-experiments.git`.

**Comment by rahul-1209** [comment]
Great! Thanks @cwognum @David-Araripe. 
Congratulations on the paper. The study is focused on a very important problem to minimize the gap between testing and deployment in drug discovery. Looking forward to run mood-experiments on the datasets.
